### PR TITLE
Add support for compiled rule files. Fix #2

### LINKED ISSUE #2: Cannot match against compiled rules to improve performance.
After compiling a large rules set with yarac, getting error in yaraproceesor:
p = Processor(['/etc/yara/sigcomp.yara'])

Error:
yara.SyntaxError: /etc/yara/sigcomp.yara(1): non-ascii character

This compiled ruleset works in yara-python but not in yaraproceesor.

### PR DESCRIPTION
**Pull request by dicato**
@systemxcom and @wxsBSD, if either of you have a moment, please test these changes report back! This commit adds support for compiled rule files.

If you are running `yaraprocessor.py` from a shell, you can now pass `--compiled` as an argument, which implies the rule file supplied to `--rules` is compiled.

Note that yara only supports loading rules from _one single compiled file_. This is reflected in yaraprocessor as well.

If you are using this library directly from your code, you can instantiate a `Processor` with compiled rules by passing the optional keyword argument:

``` python
p = Processor(['/full/path/to/rules, relative/path/to/other/rules'], compiled=True)
```

I've tried to improve the exception handling when providing compiled rules _without_ the appropriate configuration and vice versa.

If this works for you, just reply to this pull request and I will merge!

### CODE REVIEW

**Comment by wxsBSD** [comment]
If you're happy with the code just merge it.

**Comment by dicato** [comment]
I wanted to ensure the additions actually addressed the use case. Additionally, I wouldn't mind if someone else tested it. :smile:

I'll merge.

**Comment by systemxcom** [comment]
Hello,
I have been out. I am on it today.  Will test and communicate by Friday.  Sorry for delay.  Thank you so much!

**Comment by dicato** [comment]
You're welcome. I'm excited to hear any feedback you might have.

I've merged this code into master, so please pull from there!

**Pull request merged**
